#!/usr/bin/env bash
# service_manager.sh — start / stop kazanfutes services and timers
#
# usage:
#   sudo service_manager rebuild        # rebuild target wants from list
#   sudo service_manager sync           # alias for rebuild
#   sudo service_manager start          # start target, then report how it went
#   sudo service_manager recover        # restart missing timers and continuous services
#   sudo service_manager install-recovery
#   sudo service_manager uninstall-recovery
#   sudo service_manager stop           # graceful stop
#   sudo service_manager stop now       # fast stop + SIGKILL fallback
#   sudo service_manager report         # one-line status for each unit
#   sudo service_manager report live    # live-updating status, every 5 seconds
#   sudo service_manager report live 2  # live-updating status, every 2 seconds
#   sudo service_manager validate       # check whether listed units exist
#   sudo service_manager -help
#   sudo service_manager --help
#   sudo service_manager -usage
#   sudo service_manager --usage
#
# list of units: /media/pi/program_stick/kazanfutes/services/services_and_timers.list
# one unit per line, blanks and # comments ignored

set -u

MOUNT_POINT=/media/pi/program_stick
MANAGER_PATH=$MOUNT_POINT/kazanfutes/services/service_manager.sh
LIST=$MOUNT_POINT/kazanfutes/services/services_and_timers.list
STATE_DIR=/var/lib/kazanfutes
DESIRED_STATE_FILE=$STATE_DIR/desired_state
MONITOR_DIR=$STATE_DIR/unit_monitor
NOTIFY_AFTER_SECONDS=${KAZANFUTES_NOTIFY_AFTER_SECONDS:-600}
TARGET_NAME=kazanfutes.target
TARGET=/etc/systemd/system/$TARGET_NAME
WANTS=/etc/systemd/system/$TARGET_NAME.wants
MOUNT=media-pi-program_stick.mount
RECOVERY_SERVICE=kazanfutes-recover.service
RECOVERY_TIMER=kazanfutes-recover.timer
RECOVERY_SERVICE_PATH=/etc/systemd/system/$RECOVERY_SERVICE
RECOVERY_TIMER_PATH=/etc/systemd/system/$RECOVERY_TIMER

RED=$'\e[31m'
GREEN=$'\e[32m'
YELLOW=$'\e[33m'
RESET=$'\e[0m'

#------------------------------------------------------------
usage() {
cat <<EOF
usage:
  $0 rebuild          rebuild target wants from list
  $0 sync             alias for rebuild
  $0 start            start target, then report how it went
  $0 recover          restart missing timers and continuous services if mount is present
  $0 install-recovery install and enable the independent recovery timer
  $0 uninstall-recovery disable and remove the independent recovery timer
  $0 stop             graceful stop of listed units
  $0 stop now         fast stop + SIGKILL fallback
  $0 report           one-line status for each listed unit
  $0 report live      live-updating status, refresh every 5 seconds
  $0 report live N    live-updating status, refresh every N seconds
  $0 validate         show whether listed units exist
  $0 -help|--help|-usage|--usage
EOF
}

die() {
    echo "$*" >&2
    exit 1
}

ensure_state_dir() {
    mkdir -p "$STATE_DIR"
}

set_desired_state() {
    ensure_state_dir
    printf '%s\n' "$1" >"$DESIRED_STATE_FILE"
}

desired_state() {
    if [ -f "$DESIRED_STATE_FILE" ]; then
        sed -n '1p' "$DESIRED_STATE_FILE"
    else
        printf 'running\n'
    fi
}

ensure_list_exists() {
    [ -f "$LIST" ] || die "missing unit list: $LIST"
}

unit_lines() {
    ensure_list_exists
    sed -e 's/[[:space:]]*$//' "$LIST" \
    | grep -v '^[[:space:]]*$' \
    | grep -v '^[[:space:]]*#'
}

ensure_target_exists() {
    # This target is generated by this script, so rebuild keeps it current.
cat >"$TARGET" <<EOF
[Unit]
Description=kazanfutes services and timers
Requires=$MOUNT
BindsTo=$MOUNT
After=$MOUNT

[Install]
WantedBy=multi-user.target
EOF
}

unit_exists() {
    local unit="$1"
    systemctl cat "$unit" >/dev/null 2>&1
}

clear_wants_dir() {
    mkdir -p "$WANTS"
    find "$WANTS" -mindepth 1 -maxdepth 1 -type l -exec rm -f {} +
}

rebuild_wants() {
    ensure_list_exists
    ensure_target_exists
    clear_wants_dir

    local missing=0

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue

        if [[ "$unit" == *.service ]] && service_has_timer "$unit"; then
            printf '%sskipped%s %s (timer-backed; target uses %s)\n' \
                "$YELLOW" "$RESET" "$unit" "${unit%.service}.timer"
            continue
        fi

        if unit_exists "$unit"; then
            if systemctl add-wants "$TARGET_NAME" "$unit" >/dev/null 2>&1; then
                printf '%slinked%s %s\n' "$GREEN" "$RESET" "$unit"
            else
                printf '%sfailed%s %s\n' "$RED" "$RESET" "$unit"
                missing=1
            fi
        else
            printf '%smissing%s %s\n' "$YELLOW" "$RESET" "$unit"
            missing=1
        fi
    done < <(unit_lines)

    systemctl daemon-reload
    return $missing
}

unit_in_list() {
    local wanted="$1"
    local unit

    while IFS= read -r unit; do
        [ "$unit" = "$wanted" ] && return 0
    done < <(unit_lines)

    return 1
}

service_has_timer() {
    local unit="$1"

    [[ "$unit" == *.service ]] || return 1
    unit_in_list "${unit%.service}.timer"
}

unit_should_be_monitored() {
    local unit="$1"

    [[ "$unit" == *.timer ]] && return 0
    [[ "$unit" == *.service ]] || return 1
    service_has_timer "$unit" && return 1
    return 0
}

unit_is_healthy() {
    local unit="$1"
    local state

    state=$(systemctl is-active "$unit" 2>/dev/null || true)
    case "$state" in
        active|activating|reloading|waiting)
            return 0
            ;;
    esac

    return 1
}

unit_state_summary() {
    local unit="$1"
    local active sub load result

    active=$(systemctl show -p ActiveState --value "$unit" 2>/dev/null || true)
    sub=$(systemctl show -p SubState --value "$unit" 2>/dev/null || true)
    load=$(systemctl show -p LoadState --value "$unit" 2>/dev/null || true)
    result=$(systemctl show -p Result --value "$unit" 2>/dev/null || true)

    printf 'ActiveState=%s\nSubState=%s\nLoadState=%s\nResult=%s\n' \
        "${active:--}" "${sub:--}" "${load:--}" "${result:--}"
}

unit_monitor_key() {
    printf '%s' "$1" | tr '/ ' '__'
}

send_admin_email() {
    local subject="$1"
    local body="$2"

    if ! command -v python3 >/dev/null 2>&1; then
        printf '%spython3 missing%s; could not notify admin\n' "$RED" "$RESET" >&2
        return 1
    fi

    KAZANFUTES_EMAIL_SUBJECT="$subject" \
    KAZANFUTES_EMAIL_BODY="$body" \
    PYTHONPATH="$MOUNT_POINT/kazanfutes" \
    python3 -c 'import os; from utils.project import notify_admin; notify_admin(subject=os.environ["KAZANFUTES_EMAIL_SUBJECT"], body=os.environ["KAZANFUTES_EMAIL_BODY"])' \
        >/dev/null 2>&1
}

notify_unit_outage() {
    local unit="$1"
    local elapsed="$2"
    local down_since="$3"
    local now_iso down_iso subject body

    now_iso=$(date --iso-8601=seconds 2>/dev/null || date)
    down_iso=$(date --date="@$down_since" --iso-8601=seconds 2>/dev/null || printf '%s' "$down_since")
    subject="Kazanfutes unit not running: $unit"

    body=$(cat <<EOF
Kazanfutes expected this unit to be active, but it has been unhealthy long enough to trigger an alert.

Unit: $unit
Down since: $down_iso
Elapsed seconds: $elapsed
Checked at: $now_iso
Notify threshold seconds: $NOTIFY_AFTER_SECONDS

Current systemd state:
$(unit_state_summary "$unit")

The recovery timer will keep trying to restart expected-active units.

Useful commands:
  systemctl status $unit
  journalctl -u $unit --since '$down_iso' --no-pager
  /media/pi/program_stick/kazanfutes/services/service_manager.sh report
EOF
)

    send_admin_email "$subject" "$body"
}

notify_unit_recovery() {
    local unit="$1"
    local down_since="$2"
    local last_notified="$3"
    local now now_iso down_iso notified_iso elapsed subject body

    now=$(date +%s)
    now_iso=$(date --iso-8601=seconds 2>/dev/null || date)
    down_iso=$(date --date="@$down_since" --iso-8601=seconds 2>/dev/null || printf '%s' "$down_since")
    notified_iso=$(date --date="@$last_notified" --iso-8601=seconds 2>/dev/null || printf '%s' "$last_notified")
    elapsed=$((now - down_since))
    subject="Kazanfutes unit recovered: $unit"

    body=$(cat <<EOF
Kazanfutes expected this unit to be active, previously sent an outage alert, and now sees it as healthy again.

Unit: $unit
Down since: $down_iso
Outage alert sent: $notified_iso
Recovered at: $now_iso
Elapsed seconds: $elapsed

Current systemd state:
$(unit_state_summary "$unit")

Useful commands:
  systemctl status $unit
  journalctl -u $unit --since '$down_iso' --no-pager
  /media/pi/program_stick/kazanfutes/services/service_manager.sh report
EOF
)

    send_admin_email "$subject" "$body"
}

monitor_expected_units() {
    local unit now key unit_dir down_file notified_file down_since elapsed last_notified

    [ "$(desired_state)" = "running" ] || return 0
    mountpoint -q "$MOUNT_POINT" || return 0
    [ -f "$LIST" ] || return 0

    mkdir -p "$MONITOR_DIR"
    now=$(date +%s)

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue
        unit_should_be_monitored "$unit" || continue

        key=$(unit_monitor_key "$unit")
        unit_dir="$MONITOR_DIR/$key"
        down_file="$unit_dir/down_since"
        notified_file="$unit_dir/last_notified"

        if unit_is_healthy "$unit"; then
            if [ -f "$notified_file" ]; then
                down_since=$(sed -n '1p' "$down_file" 2>/dev/null || printf '%s' "$now")
                last_notified=$(sed -n '1p' "$notified_file" 2>/dev/null || printf '%s' "$now")
                case "$down_since" in
                    ''|*[!0-9]*) down_since=$now ;;
                esac
                case "$last_notified" in
                    ''|*[!0-9]*) last_notified=$now ;;
                esac
                notify_unit_recovery "$unit" "$down_since" "$last_notified" || true
            fi
            rm -rf "$unit_dir"
            continue
        fi

        mkdir -p "$unit_dir"

        if [ ! -f "$down_file" ]; then
            printf '%s\n' "$now" >"$down_file"
            continue
        fi

        down_since=$(sed -n '1p' "$down_file")
        case "$down_since" in
            ''|*[!0-9]*)
                down_since=$now
                printf '%s\n' "$now" >"$down_file"
                ;;
        esac

        elapsed=$((now - down_since))
        [ "$elapsed" -ge "$NOTIFY_AFTER_SECONDS" ] || continue

        [ ! -f "$notified_file" ] || continue

        if notify_unit_outage "$unit" "$elapsed" "$down_since"; then
            printf '%s\n' "$now" >"$notified_file"
            printf '%snotified admin%s %s has been unhealthy for %ss\n' \
                "$YELLOW" "$RESET" "$unit" "$elapsed"
        else
            printf '%sfailed to notify admin%s %s has been unhealthy for %ss\n' \
                "$RED" "$RESET" "$unit" "$elapsed"
        fi
    done < <(unit_lines)
}

reset_failed_units() {
    local unit

    systemctl reset-failed "$TARGET_NAME" "$MOUNT" 2>/dev/null || true

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue
        systemctl reset-failed "$unit" 2>/dev/null || true
    done < <(unit_lines)
}

start_unit_if_needed() {
    local unit="$1"
    local state
    local quiet="${KAZANFUTES_RECOVER_QUIET:-0}"

    if ! unit_exists "$unit"; then
        printf '%smissing%s %s\n' "$YELLOW" "$RESET" "$unit"
        return 1
    fi

    state=$(systemctl is-active "$unit" 2>/dev/null || true)

    case "$state" in
        active|activating|reloading|waiting)
            if [ "$quiet" != "1" ]; then
                printf '%salready %s%s %s\n' "$GREEN" "$state" "$RESET" "$unit"
            fi
            return 0
            ;;
    esac

    if systemctl start "$unit"; then
        printf '%sstarted%s %s\n' "$GREEN" "$RESET" "$unit"
        return 0
    fi

    printf '%sfailed to start%s %s\n' "$RED" "$RESET" "$unit"
    return 1
}

start_missing_units() {
    local unit missing=0

    # Timers are the steady-state launcher for scheduled jobs.
    while IFS= read -r unit; do
        [ -z "$unit" ] && continue
        [[ "$unit" == *.timer ]] || continue
        start_unit_if_needed "$unit" || missing=1
    done < <(unit_lines)

    # Services that have a matching timer should normally stay inactive between
    # timer firings. Start only continuous services here.
    while IFS= read -r unit; do
        [ -z "$unit" ] && continue
        [[ "$unit" == *.service ]] || continue
        service_has_timer "$unit" && continue
        start_unit_if_needed "$unit" || missing=1
    done < <(unit_lines)

    return $missing
}

recover_units() {
    if [ "$(desired_state)" != "running" ]; then
        if [ "${KAZANFUTES_RECOVER_QUIET:-0}" != "1" ]; then
            printf '%sdesired state is stopped%s; recovery skipped\n' "$YELLOW" "$RESET"
        fi
        return 0
    fi

    if ! mountpoint -q "$MOUNT_POINT"; then
        if [ "${KAZANFUTES_RECOVER_QUIET:-0}" != "1" ]; then
            printf '%smount absent%s %s; recovery skipped\n' "$YELLOW" "$RESET" "$MOUNT_POINT"
        fi
        return 0
    fi

    if [ ! -f "$LIST" ]; then
        if [ "${KAZANFUTES_RECOVER_QUIET:-0}" != "1" ]; then
            printf '%smissing unit list%s %s; recovery skipped\n' "$YELLOW" "$RESET" "$LIST"
        fi
        return 0
    fi

    reset_failed_units
    start_missing_units || true
    monitor_expected_units
}

install_recovery_units() {
    ensure_state_dir

cat >"$RECOVERY_SERVICE_PATH" <<EOF
[Unit]
Description=Recover kazanfutes services after mount or service interruption

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'mountpoint -q $MOUNT_POINT && exec env KAZANFUTES_RECOVER_QUIET=1 /bin/bash $MANAGER_PATH recover || exit 0'
EOF

cat >"$RECOVERY_TIMER_PATH" <<EOF
[Unit]
Description=Periodically recover kazanfutes services

[Timer]
OnBootSec=1min
OnUnitActiveSec=1min
AccuracySec=15s
Persistent=true

[Install]
WantedBy=timers.target
EOF

    rebuild_wants || true
    systemctl daemon-reload
    systemctl enable --now "$RECOVERY_TIMER"
    printf '%sinstalled%s %s and %s\n' "$GREEN" "$RESET" "$RECOVERY_SERVICE" "$RECOVERY_TIMER"
}

uninstall_recovery_units() {
    systemctl disable --now "$RECOVERY_TIMER" 2>/dev/null || true
    rm -f "$RECOVERY_SERVICE_PATH" "$RECOVERY_TIMER_PATH"
    systemctl daemon-reload
    printf '%sremoved%s %s and %s\n' "$RED" "$RESET" "$RECOVERY_SERVICE" "$RECOVERY_TIMER"
}

stop_units() {
    local unit

    set_desired_state stopped
    rm -rf "$MONITOR_DIR"
    systemctl stop "$TARGET_NAME" 2>/dev/null || true

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue
        [[ "$unit" == *.timer ]] || continue
        if unit_exists "$unit"; then
            systemctl stop "$unit"
        fi
    done < <(unit_lines)

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue
        [[ "$unit" == *.service ]] || continue
        if unit_exists "$unit"; then
            systemctl stop "$unit"
        fi
    done < <(unit_lines)
}

kill_units() {
    local unit

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue
        [[ "$unit" == *.service ]] || continue
        if unit_exists "$unit"; then
            systemctl kill --signal=SIGKILL "$unit" 2>/dev/null || true
        fi
    done < <(unit_lines)
}

report_stop() {
    local ok=true

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue

        if ! unit_exists "$unit"; then
            printf '%s%s missing%s\n' "$YELLOW" "$unit" "$RESET"
            ok=false
            continue
        fi

        if systemctl is-active --quiet "$unit"; then
            printf '%s%s still running%s\n' "$GREEN" "$unit" "$RESET"
            ok=false
        else
            printf '%s%s stopped%s\n' "$RED" "$unit" "$RESET"
        fi
    done < <(unit_lines)

    if $ok; then
        printf '%sall units stopped%s\n' "$RED" "$RESET"
    else
        printf '%ssome units still active or missing%s\n' "$GREEN" "$RESET"
    fi
}

report_units() {
    local unit state display_state load color last next start exit_ts

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue

        if ! unit_exists "$unit"; then
            printf '%s%-35s | %-8s%s\n' "$YELLOW" "$unit" "missing" "$RESET"
            continue
        fi

        state=$(systemctl is-active "$unit" 2>/dev/null)
        display_state=$state
        load=$(systemctl show -p LoadState --value "$unit" 2>/dev/null)
        color=$RED

        [[ "$state" == "active" || "$state" == "waiting" ]] && color=$GREEN
        if [[ "$unit" == *.service ]] && service_has_timer "$unit" && [[ "$state" == "inactive" ]]; then
            color=$GREEN
            display_state=timer-managed
        fi

        if [[ $unit == *.timer ]]; then
            last=$(systemctl show -p LastTriggerUSec --value "$unit" 2>/dev/null)
            next=$(systemctl show -p NextElapseUSec --value "$unit" 2>/dev/null)

            printf '%s%-35s | %-8s | load: %-6s | last: %s | next: %s%s\n' \
                "$color" "$unit" "$display_state" "$load" "${last:--}" "${next:--}" "$RESET"
        else
            start=$(systemctl show -p ExecMainStartTimestamp --value "$unit" 2>/dev/null)
            exit_ts=$(systemctl show -p ExecMainExitTimestamp --value "$unit" 2>/dev/null)

            printf '%s%-35s | %-8s | load: %-6s | started: %s | exit: %s%s\n' \
                "$color" "$unit" "$display_state" "$load" "${start:--}" "${exit_ts:--}" "$RESET"
        fi
    done < <(unit_lines)
}

report_live_cleanup() {
    tput cnorm 2>/dev/null || true
    tput rmcup 2>/dev/null || true
    printf '\n'
}

report_live() {
    local interval="${1:-5}"
    local screen body now

    if ! [[ "$interval" =~ ^[0-9]+$ ]] || [ "$interval" -lt 1 ]; then
        die "refresh interval must be a positive integer number of seconds"
    fi

    trap 'report_live_cleanup; exit 130' INT TERM
    trap 'report_live_cleanup' EXIT

    # alternate screen + hidden cursor
    tput smcup 2>/dev/null || true
    tput civis 2>/dev/null || true

    # initial wipe only once
    printf '\e[2J'

    while true; do
        now=$(date '+%Y-%m-%d %H:%M:%S')
        body=$(report_units)

        screen=$(printf 'kazanfutes live report | %s | refresh: %ss | Ctrl-C to quit\n\n%s\n' \
            "$now" "$interval" "$body")

        # move cursor home, draw full buffered screen, clear leftover old lines
        printf '\e[H%s\e[J' "$screen"

        sleep "$interval"
    done
}

validate_units() {
    local missing=0

    while IFS= read -r unit; do
        [ -z "$unit" ] && continue

        if unit_exists "$unit"; then
            printf '%sok%s %s\n' "$GREEN" "$RESET" "$unit"
        else
            printf '%smissing%s %s\n' "$YELLOW" "$RESET" "$unit"
            missing=1
        fi
    done < <(unit_lines)

    return $missing
}

start_target() {
    local target_state

    set_desired_state running
    if unit_exists "$RECOVERY_TIMER"; then
        systemctl start "$RECOVERY_TIMER" 2>/dev/null || true
    fi

    printf 'rebuilding %s wants ...\n' "$TARGET_NAME"
    rebuild_wants || true
    reset_failed_units

    printf 'starting %s ...\n' "$TARGET_NAME"

    if systemctl start "$TARGET_NAME"; then
        printf '%sstart command succeeded%s for %s\n' "$GREEN" "$RESET" "$TARGET_NAME"
    else
        printf '%sstart command failed%s for %s\n' "$RED" "$RESET" "$TARGET_NAME"
    fi

    target_state=$(systemctl is-active "$TARGET_NAME" 2>/dev/null || true)
    printf 'target state: %s\n' "${target_state:--}"

    echo
    if mountpoint -q "$MOUNT_POINT"; then
        echo "recovering inactive timers and continuous services:"
        start_missing_units || true
        monitor_expected_units
    else
        echo "mount is absent; inactive unit recovery skipped"
    fi

    echo
    echo "unit status after start:"
    report_units
}

case "${1:-}" in
  rebuild|sync)
        rebuild_wants
        ;;
  start)
        start_target
        ;;
  recover)
        recover_units
        ;;
  install-recovery)
        install_recovery_units
        ;;
  uninstall-recovery)
        uninstall_recovery_units
        ;;
  stop)
        stop_units
        [ "${2:-}" = "now" ] && kill_units
        report_stop
        ;;
  report)
        if [ "${2:-}" = "live" ]; then
            report_live "${3:-5}"
        else
            report_units
        fi
        ;;
  validate)
        validate_units
        ;;
  -help|--help|-usage|--usage|help|usage)
        usage
        ;;
  *)
        usage >&2
        exit 1
        ;;
esac
